### ISSUE TITLE
Basic filters may misinterpret numeric types, which will fail in postgres

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/soda-carto#23]
Example: [incidents_part1_part2?dc_dist=24](https://z8c5187y6e.execute-api.us-east-1.amazonaws.com/dev/resource/incidents_part1_part2?dc_dist=24)

The table's `dc_dist` column is a string, but `node-soda2-parser` treats this basic filter's value as a number ([code](https://github.com/timwis/node-soda2-parser/blob/master/index.js#L8)). The result is a postgres query `WHERE dc_dist = 24`, which throws an error.

@andrewbt do you think it would be wise to _always_ treat these values as strings? For instance, if `dc_dist` where actually an _integer_ field in the table, and we queried as if it were a string (`WHERE dc_dist = '24'`), it seems like that would work fine. The only other types I can think of are booleans, floats, and date/times. Can we query those as strings too?

**Comment by andrewbt** [comment]
@timwis done some research/basic tests on this.

1. `where booleancolumn = 'true'` works
2. `where datecolumn = '2016-01-01'` works
3. `where stringcolumn = 'text'` works
4. `where intcolumn = '234'` works

Want to do more testing / ask more people tomorrow before I'm confident in a solution that involves "just quote everything", but preliminary results are positive. It seems the above work though because of Postgres' "implicit conversion" rules - quoted literals are treated as `unknown` type and casted to the appropriate column type when compared with the equality operator.

Some links:
http://stackoverflow.com/questions/19469154/how-to-compare-dates-in-datetime-fields-in-postgresql/19469209#19469209
http://stackoverflow.com/questions/543580/equals-vs-like

If we need to do the "Second round trip":
http://stackoverflow.com/questions/2146705/select-datatype-of-the-field-in-postgres

I also think there's a possibility for adding more information to datasets.yml and using that, rather than a round trip. For instance, if datasets.yml had information like "dc_dist is a string column", could we use that to make sure the query was properly quoted?

**Comment by timwis** [comment]
Thanks @andrewbt, that's great to hear. Hopefully floats work too. The `datasets.yml` idea would definitely work - good thinking. It would just be a lot more work up front to get all the info in there. May end up being worth it, but perhaps it's not necessary.

I've patched this in node-soda2-parser in the below referenced pull request. Once I hear from you, @andrewbt, we can merge it.
